### ISSUE TITLE
ObsCollection.from_knmi()

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/observations#14]
ObsCollection does not yet have any methods for downloading KNMI data, which would be nice to have.

I propose something along these lines:
`ObsCollection.from_knmi(stns=None, df=None, variable="RD")`

So both a list of stations can be entered or another dataframe with 'x' and 'y' columns.

**Comment by OnnoEbbens** [comment]
I created this method in my latest commit to `dev`. This makes it a lot easier to add knmi stresses to a pastastore:

```
oc= ObsCollection.from_dino(extent=extent)
knmi_oc = ObsCollection.from_knmi(locations=oc, meteo_vars=["EV24"])
pstore = oc.to_pastastore()
knmi_oc.to_pastastore(pstore, obs_column="EV24", kind="evap")
```
