### ISSUE TITLE
obs_from_pystore fails after updating pystore

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/observations#27]
After I updated the pystore package from 0.1.9 to 0.1.14 I get an `IndexError: list index out of range` error when running the following code (from the test_001.py):

```
import pystore
pystore.set_path("./tests/data/2019-Pystore-test")
store = pystore.store("test_pystore")
coll = store.collection(store.collections[0])
```

apparently `store.collections` is an empty list.

**Comment by dbrakenhoff** [comment]
I was getting the same error, but to be fair, the pystore is empty after cloning the repository. 

I need to run some other tests first before there are any collections in there. But for me it works fine... after doing that. I'm currently on pystore version 0.1.15.

**Comment by OnnoEbbens** [comment]
Ah yes when updating to 1.1.15 everything works fine. Should have tried that first, sorry.
